### PR TITLE
Proximity_detectors

### PR DESCRIPTION
**Pull request by DavidCendanG**

### CODE REVIEW

**Comment by OgLocGreen** [comment]
@DavidCendanG  please check if this Pull request was merged right. (if your code is the main and that it works fine)

**Comment by DavidCendanG** [comment]
I don't have the BBB to try the code, but it looks like the last version that i requested to Pull.

**Comment by DavidCendanG** [comment]
@OgLocGreen

**Comment by OgLocGreen** [comment]
okay perfe

**Pull request merged**
